### PR TITLE
Django 3.0 support

### PR DESCRIPTION
**Pull request by valberg**
Fixing small issue with django.utils.curry being removed in Django 3.0. 
Dropped support for anything below Django 2.2 and Python 3.6.

### CODE REVIEW

**Comment by valberg** [comment]
@kmmbvnr Do you have the time to look at this? I'm glad to help with releasing a new version if you need help! :)

**Comment by kmmbvnr** [comment]
Thanks for the PR! But I prefer do not drop older django/python versions.

**Comment by valberg** [comment]
@kmmbvnr Roger! I can fix it up so they are supported?

**Comment by valberg** [comment]
Ah you already fixed it, great! Thanks for a great package @kmmbvnr! :+1:

**Pull request closed without merging**
